### ISSUE TITLE
SJSC07 – Lock Pragmas to Specific Compiler Version

### ISSUE THREAD

**Issue by Reg0x** [Solidity-Jobs/S-Token#13]
Contracts should be deployed with the same versions and compiler flags with 
which they have been tested.

Blocking pragmas to a specific version can avoid risks of using the latest 
compiler versions that may contain recent or undiscovered bugs.

**Comment by Reg0x** [comment]
• https://swcregistry.io/docs/SWC-103

**Comment by solidityjobsdev** [comment]
Pragmas locked in the main 3 files + lockedCRPNT
