### ISSUE TITLE
SJSC09 – GAS Optimization (Informative)

### ISSUE THREAD

**Issue by Reg0x** [Solidity-Jobs/S-Token#15]
Software optimization is the process of modifying a software system to make an 
aspect of it work more efficiently or use less resources. This premise must be 
applied to smart contracts as well, so that they execute faster or in order to save 
GAS.
On Ethereum blockchain, GAS is an execution fee which is used to compensate 
miners for the computational resources required to power smart contracts. If the 
network usage is increasing, so will the value of GAS optimization.
These are some of the requirements that must be met to reduce GAS 
consumption:
Solidity Jobs Smart Contracts Audit

• Short-circuiting.
• Remove redundant or dead code.
• Delete unnecessary libraries.
• Explicit function visibility.
• Use of proper data types.
• Use hard-coded CONSTANT instead of state variables.
• Avoid expensive operations in a loop.
• Pay special attention to arithmetical operations and comparison

**Comment by Reg0x** [comment]
https://github.com/Solidity-Jobs/S-Token/blob/44363c599da7b19ee922be33816edbeacffa2139/token/ERC20/ERC2

**Comment by Reg0x** [comment]
Storage Optimization
The use of the immutable2 keyword is recommended to obtain less expensive 
executions, by having the same behaviour as a constant. However, by defining 
its value in the constructor we have a significant save of GAS.
This behaviour has been observed in las variables _name and _symbol of the
ERC20.sol contract.

**Comment by Reg0x** [comment]
Pure Methods
In order to save execution costs, it is recommended to turn the decimals function 
of ERC20 contract to type pure. 
pure could be considered a constant where the return value will only be 
determined by the input parameters. It will not be possible to read or write in the 
storage and only a local variable will be used.

**Comment by solidityjobsdev** [comment]
The recommended changes are on name, symbol and decimals, functions that do not interact with the rest of functions. Additionally, they are extracted directly from OpenZeppelin's code, therefore no modifications will be applied.
