### ISSUE TITLE
SJSC01 – Unsecure feeReceiver Change (Low)

### ISSUE THREAD

**Issue by Reg0x** [Solidity-Jobs/S-Token#7]
The modification process of a feeReceiver is a delicate process, since the funding 
of the project or its continuity can be at risk, for this reason it is recommended 
to adjust the modification logic, to a logic that allows to verify that the new 
address is in fact valid and does exist.

Following, it would be convenient to consider using the AccessControl to simplify 
and unify these types of modifications and to avoid human errors that may later 
occur. For example, a missing zero address validation was detected in the 
constructor, which would make it impossible to change the feeReceiver address 
in the future.

**Comment by Reg0x** [comment]
https://github.com/Solidity-Jobs/S-Token/blob/44363c599da7b19ee922be33816edbeacffa2139/CRPNT.sol#L71

**Comment by Reg0x** [comment]
https://github.com/Solidity-Jobs/S-Token/blob/44363c599da7b19ee922be33816edbeacffa2139/CRPNT.sol#L22

**Comment by solidityjobsdev** [comment]
Solved in #19
