### ISSUE TITLE
SJSC03 – Lack of Inputs Validation (Informative)

### ISSUE THREAD

**Issue by Reg0x** [Solidity-Jobs/S-Token#9]
Some methods of the different contracts in the CRPNT project do not properly 
check the arguments, which can lead to major errors.

During the constructor’s logic of the contract, none of the received arguments 
are verified; for example, in case of receiving a _feeReceiver with the value of 

_address(0)_, it could not be modified afterwards, as it has been mentioned in the 
Unsecure feeReceiver change issue.

**Comment by Reg0x** [comment]
https://github.com/Solidity-Jobs/S%02Token/blob/44363c599da7b19ee922be33816edbeacffa2139/CRPNT.sol#L20

**Comment by Reg0x** [comment]
https://github.com/Solidity-Jobs/S-Token/blob/44363c599da7b19ee922be33816edbeacffa2139/CRPNT.sol#L20

**Comment by Reg0x** [comment]
https://github.com/Solidity-Jobs/S-Token/blob/44363c599da7b19ee922be33816edbeacffa2139/CRPNT.sol#L70

**Comment by solidityjobsdev** [comment]
Solved in #19
